/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tangyin_mobile_ges_jnidemo_MainActivity */

#ifndef _Included_com_tangyin_mobile_ges_jnidemo_MainActivity
#define _Included_com_tangyin_mobile_ges_jnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tangyin_mobile_ges_jnidemo_MainActivity
 * Method:    fork
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tangyin_mobile_ges_jnidemo_MainActivity_fork
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
